name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Clojure
      run: build/install-clojure
    - name: Set up credentials
      env:
        USERNAME: ${{ secrets.MAVEN_USERNAME }}
        PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: build/setup-credentials
    - name: Run test
      run: clojure -A:test
    - name: Generate Uberjar
      run: clojure -A:uberjar --app-version `mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
    - name: Deploy clojars
      run: mvn deploy
